export const UI_ICONS = {
  brand: 'bi-flower1',
  planning: 'bi-grid-1x2',
  timeline: 'bi-bar-chart-steps',
  fertilization: 'bi-droplet',
  export: 'bi-download',
  calendar: 'bi-calendar-event',
  print: 'bi-printer',
  sowing: 'bi-flower1',
  transplanting: 'bi-box-arrow-down',
  harvest: 'bi-basket',
  home: 'bi-house',
  ruler: 'bi-rulers',
  palette: 'bi-palette',
  shield: 'bi-shield-check',
  tip: 'bi-lightbulb',
  check: 'bi-check-lg',
  close: 'bi-x-lg',
  add: 'bi-plus-lg',
}
